#ifndef CONFIG_H
#define CONFIG_H

#define INPUT_SIZE 16
#define FILTER_SIZE 3
#define OUTPUT_SIZE (INPUT_SIZE-FILTER_SIZE)+1
#define POOL_SIZE 2
#define POOL_OUTPUT_SIZE (OUTPUT_SIZE/POOL_SIZE)
#define FLAT_SIZE (POOL_OUTPUT_SIZE*POOL_OUTPUT_SIZE)

#endif